securekey: "ChangeThisKeyAfterInstall"

bungeecord:
  authserver: "authserver"
  login:
    algo: sha512
    kickonwrongpwd: true
    nick:
      regex: "[a-zA-Z0-9_?]*"
      maxlength: 16
      minlength: 2
    timeout: 20
    helpmsginterval: 2
    maxregsperip: 3
    messages:
      register:
        already: "&cUsername already registered"
        error: "&fAn error occurred while registering; Please contact the admin"
        success: "&eSuccessfully registered!"
        help: "&cPlease register with /register password"
        max: "&fYou have exceeded the max number of registrations for your ip"
      login:
        already: "&cAlready logged in"
        success: "&eSuccessful login!"
        error: "&fAn error occurred while login; Please contact the admin"
        wrongpwd: "&cWrong password"
        help: "&cPlease login with /login password"
      passwordchange:
        wrongpwd: "&cWrong old password"
        success: "&ePassword changed!"
        error: "&fAn error occurred while changing password; Please contact the admin"
      timedout: "&fLogin Timeout"
      unknownuser: "&fUser is not in database"
      noperms: "&cNo Permission"
      restriction:
        namelength: "&cYour nickname is too short or too long"
        regex: "&cYour nickname contains illegal characters. Allowed chars: REG_EX"
        invalidcase: "&cPlease log in using valid name case: REALNAME"
        alreadyplaying: "&cAlready logged in!"
      optsecurity:
        hostname:
          wrong: "&cJoined hostname doesn't match"
          set: "&eJoin hostname set"
          removed: "&eJoin hostname removed"
        license:
          enabled: "&eLicense mode enabled"
          disabled: "&eLicense mode disabled"
  messages:
    notloggedin: "&4Login first"

gameserver:
  messages:
    timeout: "&4Timeout while receiving secure key, please make sure that you authenticated in lobby"
    missmatch: "&4Invalid secure key received, please make sure that gameserver and bungeecord secure keys match"
